language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
#  - hhvm

env:
  - SYMFONY_VERSION=2.6.*
  - SYMFONY_VERSION=2.7.*
#  - SYMFONY_VERSION=dev-master

before_script:
  - composer require symfony/dom-crawler:${SYMFONY_VERSION}
  - composer require symfony/css-selector:${SYMFONY_VERSION}

script: phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

